<?php 
/**
Template Page for the gallery overview

Follow variables are useable :

	$gallery     : Contain all about the gallery (object type stdClass)
This object can have the following values:
        ->ID                : Gallery ID (integer)
        ->show_slideshow    : true|false. If it is true, there are two more properties available:
            ->slideshow_link    : link for slideshow  (only present if show_slideshow exists)
            ->slideshow_link_text: link for slideshow (only present if show_slideshow exists)
        ->show_piclens      : true|false. If it is true there is another property available
            ->piclens_link      : link for piclens (javascript routine) (only if show_piclens exists)
        ->name              : gallery name (string)
        ->title             : gallery title
        ->description       : gallery description
        ->pageid            : Page Id
        ->anchor            : Unique ID generated by gallery ID and current page with format 'ngg-gallery-' . $galleryID . '-' . $current_page;
        ->columns           : number of columns(integer)
        ->imagewidth        : style for use in template format: 'style-width: floor(100/columns)'

	$images      : Contain all images, path, title
        This is a collection of image(s). Every image has the following properties:
            $image (object type nggImage)
                ->hidden    : image is hidden
                ->style     : style for image when hidden
                ->pidlink   : permalink for image
                ->metadata  : image metadata. This is an array containing:
                                    ->metadata['thumbnail'] : image thumbnail information.
                                                            This is an array containing:
                                                            ['thumbnail']['width']  : thumbnail width
                                                            ['thumbnail']['height'] : thumbnail height
                ->url       : image url
                ->imageURL  : image url where the filter ngg_create_gallery_link is applied first
                ->size      : string with picture size in the form 'width="'xxxx'" height="'yyy'"'
                ->thumbcode : thumbcode (?)
                ->caption   : image caption
                ->description: image description
                ->alttext   : image alttext
              from nggImage: errmsg,error,imageURL,thumbURL,imagePath,thumbPath,href,thumbPrefix,thumbFolder,
                            galleryid,pid,filename,description,alttext,imagedate,exclude,thumbcode,name,path,title,
                            pageid,previewpic,permalink,tags

	$pagination  : (string) Contain the pagination content (created with class nggNavigation->create_navigation)

 You can check the content when you insert the tag <?php var_dump($variable) ?>
 If you would like to show the timestamp of the image ,you can use <?php echo $exif['created_timestamp'] ?>
**/
/**
 * This is the base template for a gallery.
 *
 * Note: please edit this file carefully. Syntax errors in this file will cause PHP to stop execution,
 * and in most cases, fail silently.
 * 
 * Following variables are available for use:
 * @var NextCellent\Models\Gallery $gallery The gallery to display. It contains the images for this page.
 * @var \NextCellent\Rendering\Pagination $pagination The pagination. It implements toString, so you can just echo it.
 * @var string $anchor An id for the gallery.
 */
?>

<div class="ngg-galleryoverview" id="<?= $anchor ?>">

	<?php //if ($gallery->show_slideshow) { ?>
	<!--	<!-- Slideshow link -->-->
	<!--	<div class="slideshowlink">-->
	<!--		<a class="slideshowlink" href="--><?php //echo $gallery->slideshow_link ?><!--">-->
	<!--			--><?php //echo $gallery->slideshow_link_text ?>
	<!--		</a>-->
	<!--	</div>-->
	<?php //} ?>

	<?php //if ($gallery->show_piclens) { ?>
	<!--	<!-- Piclense link -->-->
	<!--	<div class="piclenselink">-->
	<!--		<a class="piclenselink" href="--><?php //echo $gallery->piclens_link ?><!--">-->
	<!--			--><?php //esc_html_e('[View with PicLens]','nggallery'); ?>
	<!--		</a>-->
	<!--	</div>-->
	<?php //} ?>

	<!-- Thumbnails -->
	<?php foreach ( $gallery->images as $image ) : ?>

	<div id="ngg-image-<?= $image->id ?>" class="ngg-gallery-thumbnail-box">
		<div class="ngg-gallery-thumbnail" >
			<a href="<?= $image->url ?>" title="<?= $image->description ?>">
				<img title="<?= $image->alt_text ?>" alt="<?= $image->alt_text ?>" src="<?= $image->thumb_url ?>" />
			</a>
		</div>
	</div>

	<?php endforeach; ?>

	<!-- Pagination -->
	<?= $pagination ?>
</div>